[project]
name = "odoo-addons-oca-account-analytic"
version = "18.0.20241121.0"
dependencies = [
    "odoo-addon-account_analytic_tag==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
